## This script serves as a source to load various utility functions 

source('~/Dropbox/mlmodel_select/timeRecord_functions.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/caret_to_mlList.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/char_to_factor.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/correlation.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/fac_to_num.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/int_to_num.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/miss_name.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/miss_pct_df.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/miss_pct_plot.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/mlog.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/na_to_fac.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/select_comp.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/select_fac.R', echo=TRUE)
source('~/Dropbox/mlmodel_select/select_num.R', echo=TRUE)